Use for loop for the deployment hooks

diff --git a/.github/actions/kubernetes-rollout-restart/action.yml b/.github/actions/kubernetes-rollout-restart/action.yml
--- a/.github/actions/kubernetes-rollout-restart/action.yml
+++ b/.github/actions/kubernetes-rollout-restart/action.yml
@@ -1,5 +1,5 @@
 ﻿name: kubernetes-rollout-restart
-description: Start a rollout restart of a kubernetes deployment
+description: Start a rollout restart of Kubernetes deployments
 inputs:
   apiurl:
     required: true
@@ -7,9 +7,9 @@ inputs:
   token:
     required: true
     description: Bearer Token for Authentication (Service Account Token)
-  deployment:
+  deployments:
     required: true
-    description: Deployment name
+    description: Comma-separated list of deployment names
 
 runs:
   using: composite
@@ -18,17 +18,29 @@ runs:
     - name: Rollout Kubernetes Deployment Restart
       shell: bash
       run: |
-        curl -k -f -o /dev/null -X PATCH "${{ inputs.apiurl }}/apis/apps/v1/namespaces/default/deployments/${{ inputs.deployment }}?fieldManager=kubectl-rollout&pretty=true" \
-        --header "Content-Type: application/strategic-merge-patch+json" \
-        --header "Authorization: Bearer ${{ inputs.token }}" \
-        --data-raw '{
-          "spec": {
-            "template": {
-              "metadata": {
-                "annotations": {
-                  "kubectl.kubernetes.io/restartedAt": "'"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'"
+        IFS=',' read -ra DEPLOYMENT_ARRAY <<< "${{ inputs.deployments }}"
+        for deployment in "${DEPLOYMENT_ARRAY[@]}"; do
+          echo "Deploying to deployment: $deployment"
+          curl -k -f -o /dev/null -X PATCH "${{ inputs.apiurl }}/apis/apps/v1/namespaces/default/deployments/$deployment?fieldManager=kubectl-rollout&pretty=true" \
+          --header "Content-Type: application/strategic-merge-patch+json" \
+          --header "Authorization: Bearer ${{ inputs.token }}" \
+          --data-raw '{
+            "spec": {
+              "template": {
+                "metadata": {
+                  "annotations": {
+                    "kubectl.kubernetes.io/restartedAt": "'"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'"
+                  }
                 }
               }
             }
-          }
-        }'
+          }'
+        
+          # Check if the curl command was successful
+          if [ $? -ne 0 ]; then
+            echo "Failed to restart deployment: $deployment"
+            exit 1  # Fail the action if curl fails
+          else
+            echo "Successfully restarted deployment: $deployment"
+          fi
+        done
